# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-11 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='c_text',
        ),
    ]
